apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker-service
  template:
    metadata:
      labels:
        app: broker-service
    spec:
      containers: 
      - name: broker-service
        image: "berni23/broker-service:1.1.2"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits: 
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 9080

---

apiVersion: v1
kind: Service
metadata:
  name: broker-service
spec: 
  selector:
    app: broker-service
  ports:
    - protocol: TCP
      name: main-port
      port: 9080
      targetPort: 9080

