version: '3.7'

volumes:
   db-data:

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
      PGDATA: /pg-data
    ports:
      - "5432:5432"
    volumes:
      - db-data:/db-data

    
#docker container run -d name=postgres2 -p 5433:5433 --user $(id -u):$(id -g) -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password -v /GO_PROJECTS/go-micro/project/db-data/postgres/:/var/lib/postgresql/data postgres:latest

      
#docker container run -d --name=postgres -p 5432:5432 --user $(id -u):$(id -g) -e POSTGRES_DB=users -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -v ./db-data/postgres/:/var/lib/postgresql/data:z  postgres:latest